kannada/urls.py
from django.conf.urls import patterns, url
from kannada import views

urlpatterns = patterns('',
    url(r'^$', views.search, name='search'),
	url(r'^test/$', views.test, name='test'),
	url(r'^search_autocomplete/$', views.search_autocomplete, name='auto')
	
	
)

taglines/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^kannada/', include('kannada.urls')),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

kannada/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    name = models.CharField(max_length = 100)
    tagline = models.CharField(max_length = 250)

    def __unicode__(self):
        return self.name
    

kannada/forms.py
from django import forms
from kannada.models import Movie


class MovieForm(forms.Form):
	movie_name = forms.CharField(
				label = "Movie Name", 
        		widget = forms.TextInput()
    )

kannada/views.py
from django.shortcuts import render_to_response
from kannada.models import Movie
from kannada.forms import MovieForm
from django.template.context import RequestContext
import json
from django.http import HttpResponse

def search(request):
	try:
		movies = Movie.objects.all()
	except Movie.DoesNotExist as e:
		print e
	movie_names = []
	for movie in movies:
		movie_names.append(str(movie.name))
	if request.method == 'POST':
		form = MovieForm(request.POST)
		print form.is_valid()
		if form.is_valid():
			print form.is_valid()
			movie_name = form.cleaned_data['movie_name']
			print movie_name
			movie_description = Movie.objects.get(name = movie_name)
			print movie_description.tagline
			form = MovieForm()
			print "inside post"
			return render_to_response('index.html',locals(),context_instance=RequestContext(request))
	else:
		try:
			movies = Movie.objects.all()
		except Movie.DoesNotExist as e:
			print e
		movie_names = []
		for movie in movies:
			movie_names.append(str(movie.name))
			form = MovieForm(request.GET)
			if form.is_valid():
				movie_name = form.cleaned_data['movie_name']
				movie_description = Movie.objects.get(name = movie_name)
				print movie_description.tagline
				print "outside post"
				form = MovieForm()
	return render_to_response('index.html',locals(),context_instance=RequestContext(request))


def search_autocomplete(request):
	movie_data = []
	if request.GET.has_key(u'term'):
		value = request.GET[u'term']
		if len(value) > 1:
			movies = Movie.objects.filter(name__icontains=value)
			for movie in movies:
				movie_data.append(dict([('label', movie.name), ('value', movie.name)]))
	print movie_data
	jso = json.dumps([movie for movie in movie_data])
	print json
	return HttpResponse(jso, mimetype = 'application/json')

def test(request):
	return render_to_response('test.html')

kannada/templates/index.html
<!DOCTYPE HTML>
<html>
	<head>
		<title>Kannada Movie Taglines</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800" rel="stylesheet" type="text/css" />
		<!--[if lte IE 8]><script src="js/html5shiv.js"></script><![endif]-->
		<script src="/static/js/skel.min.js"></script>
		<script src="/static/js/skel-panels.min.js"></script>
		<script src="/static/js/init.js"></script>
  		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		<script  type="text/javascript" src="/static/js/typeahead.min.js"></script>
			<link rel="stylesheet" href="/static/css/skel-noscript.css" />-->
			<link rel="stylesheet" href="/static/css/style.css" />
			<link rel="stylesheet" href="/static/css/style-desktop.css" />
			<link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
			<link href="/static/css/typeahead.css" rel="stylesheet">
			<script type="text/javascript">
			
                	$(document).ready(function(){
                	$('input#id_movie_name').typeahead({
                		name: 'accounts',
                		local: {{ movie_names|safe }}
                		
                	});
                });  
            </script>
<style type="text/css">
.bs-example{
	font-family: sans-serif;
	position: relative;
	margin: 100px;
}
#id_movie_name, .tt-query, .tt-hint {
	border: 2px solid #CCCCCC;
	border-radius: 8px;
	font-size: 24px;
	height: 30px;
	line-height: 30px;
	outline: medium none;
	padding: 8px 12px;
	width: 396px;
}
#id_movie_name {
	background-color: #FFFFFF;
	
}
label{
	font-size : 30px;
	color : white;
}
#id_movie_name:focus {
	border: 2px solid #0097CF;
}
.tt-query {
	box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
}
.tt-hint {
	color: #999999;
	margin : 0 0 0 260px;
}
.tt-dropdown-menu {
	background-color: #FFFFFF;
	border: 1px solid rgba(0, 0, 0, 0.2);
	border-radius: 8px;
	box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
	margin-top: 12px;
	padding: 8px 0;
	width: 422px;
	margin : 0 0 0 260px;
}
.tt-suggestion {
	font-size: 24px;
	line-height: 24px;
	padding: 3px 20px;
}
.tt-suggestion.tt-is-under-cursor {
	background-color: #0097CF;
	color: #FFFFFF;
}
.tt-suggestion p {
	margin: 0;
}
</style>
		</head>
	<body class="homepage">
		<div id="header-wrapper">
		  
        	<div id="header" class="container">
            	<div id="logo"><h1><a href="/kannada/">Kannada-Movie-Taglines ;)</a></h1></div>
            </div>
			
			<div id="banner">
				<div class="container">
					<div class="row">
						<section class="12u">
							
							<header>
								<h2><b>Find your favourite movie taglines</b></h2>
								<span class="byline">Adding that extra punchline below a film title has become mandatory in almost every film in Sandalwood. Many of us watch Kannada movies. But no one bothers to relate the movie with its TAGLINES. So here is a place where you can find your favourite and hilarious taglines.</span>
							</header>
							<form action = "." method = "POST">{% csrf_token %}
							<div class="bs-example">
        					{{ form.as_p }}
    						</div>
							<input type = "submit" class="button button-alt" value = "Get the Tagline">
							</form>
                            <div class = "movie-details">
							<h2> {{ movie_description.name|upper }} - {{ movie_description.tagline }} </h2>

                            </div>
						</section>
					</div>
				</div>
			</div>			

		</div>
		<!-- Header Ends Here -->

		<!-- 
			<div id="featured-wrapper">
			
				<div class="container">
					<div class="row double">
					
                        <section class="4u">
                           <header>
	                           <h2></h2>
                           </header>
                            <span class="pennant"><span class="fa fa-apple"></span></span>
                            <p></p>
                            <a href="http://www.newindianexpress.com/entertainment/reviews/article1375734.ece" target="_blank" class="button button-style1">About taglines ;)</a>
                        </section>
                        <section class="4u">
                            <header>
	                            <h2>Suggestions</h2>
                            </header>
                            <span class="pennant"><span class="fa fa-rocket"></span></span>
                            <p></p>
                            <a href="www.facebook.com/snk300" class="button button-style1" target="_blank">Contact me</a>
                        </section>
                        <section class="4u">
                            <header>
	                            <h2>In the Making</h2>
                            </header>
                            <span class="pennant"><span class="fa fa-cogs"></span></span>
                            <p></p>
                            <a href="#" class="button button-style1">Coming Soon</a>
                        </section>
					
					</div>
				</div>
				
			</div>-->
	</body>

</html>



kannada/templates/test.html
<html>
<head>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
 
<div style="margin: 50px 50px">
    <label for="product_search">Product Search: </label>
    <input id="product_search" type="text" data-provide="typeahead"
       data-source='["Deluxe Bicycle", "Super Deluxe Trampoline", "Super Duper Scooter"]'>
</div>
 
<script src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
<script src="/static/js/bootstrap-typeahead.js"></script>
 
</body>
</html>